In [37]:
# ==============================================================================================================================================
#                                                       IMPORTING LIBRARIES
# ==============================================================================================================================================

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [38]:
df = pd.read_csv("StudentPerformanceFactors.csv")
df

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,High,Medium,No,7,76,Medium,Yes,1,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,8,81,Medium,Yes,3,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6,65,Low,Yes,3,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6,91,High,Yes,2,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9,94,Medium,Yes,0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

In [39]:
df.head(10)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70
5,19,88,Medium,Medium,Yes,8,89,Medium,Yes,3,Medium,Medium,Public,Positive,3,No,Postgraduate,Near,Male,71
6,29,84,Medium,Low,Yes,7,68,Low,Yes,1,Low,Medium,Private,Neutral,2,No,High School,Moderate,Male,67
7,25,78,Low,High,Yes,6,50,Medium,Yes,1,High,High,Public,Negative,2,No,High School,Far,Male,66
8,17,94,Medium,High,No,6,80,High,Yes,0,Medium,Low,Private,Neutral,1,No,College,Near,Male,69
9,23,98,Medium,Medium,Yes,8,71,Medium,Yes,0,High,High,Public,Positive,5,No,High School,Moderate,Male,72

In [40]:
df.shape

(6607, 20)

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6529 non-null   object
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   object
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   object
 16  Parental_Education_Level    6517 non-null   object
 17  Distance_from_Home          6540 non-null   object
 18  Gender                      6607 non-null   object
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), object(13)
memory usage: 1.0+ MB

In [42]:
# ==============================================   Calculating null values in columns   ======================================================
df.isnull().sum()

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

In [43]:
# Teacher_Quality = 78
# Distance_from_Home = 67
# Parental_Education_Level = 90

In [44]:
# =====================================         Missing column values percentage    ==========================================================

# Teacher_Quality
missing_percentage = (78/6607)*100
# 1.18%

# Distance_from_Home
missing_percentage1 = (67/6607)*100
# 1.01

# Parental_Education_Level
missing_percentage2 = (90/6607)*100
# 1.36%

# missing_percentage
# missing_percentage1
missing_percentage2

1.362191614953837

In [45]:
# ===================================================================================================================================
# Pehle hum dekhenge ki in 3 columns mein actual categories kya hain aur unki frequency kya hai.
# ===================================================================================================================================

df["Teacher_Quality"].value_counts(dropna=False)

Teacher_Quality
Medium    3925
High      1947
Low        657
NaN         78
Name: count, dtype: int64

In [46]:
df["Distance_from_Home"].value_counts(dropna = False)

Distance_from_Home
Near        3884
Moderate    1998
Far          658
NaN           67
Name: count, dtype: int64

In [47]:
df["Parental_Education_Level"].value_counts(dropna = False)

Parental_Education_Level
High School     3223
College         1989
Postgraduate    1305
NaN               90
Name: count, dtype: int64

In [48]:
#  Obtaining all categorical cols to have a look 
categorical_cols = df.select_dtypes(object).columns
categorical_cols

Index(['Parental_Involvement', 'Access_to_Resources',
       'Extracurricular_Activities', 'Motivation_Level', 'Internet_Access',
       'Family_Income', 'Teacher_Quality', 'School_Type', 'Peer_Influence',
       'Learning_Disabilities', 'Parental_Education_Level',
       'Distance_from_Home', 'Gender'],
      dtype='object')

In [49]:
#  Obtaining all numerical cols to have a look 
numerical_cols = df.select_dtypes('number').columns
numerical_cols

Index(['Hours_Studied', 'Attendance', 'Sleep_Hours', 'Previous_Scores',
       'Tutoring_Sessions', 'Physical_Activity', 'Exam_Score'],
      dtype='object')

In [50]:
#  Now fill rows with missing values as "unknown"
missing_categorical_cols = [
    "Teacher_Quality",
    "Distance_from_Home",
    "Parental_Education_Level"
]
df[missing_categorical_cols] = df[missing_categorical_cols].fillna("Unkown")

In [51]:
#  Zero missing values, as converted to "unknown"
df[missing_categorical_cols].isnull().sum()

Teacher_Quality             0
Distance_from_Home          0
Parental_Education_Level    0
dtype: int64

In [52]:
# Now lets define the model into x(input) and y (output)
x = df.drop("Exam_Score", axis = 1)
y = df["Exam_Score"]

In [53]:
# ==============================================================================================================================================
#                                               TRAIN - TEST - SPLIT
# ==============================================================================================================================================

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.2, random_state=42)

In [54]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((5285, 19), (1322, 19), (5285,), (1322,))

In [55]:
# ==============================================================================================================================================
#                                               ONE - HOT ENCODING
# ==============================================================================================================================================

# handle_unknown = ignore = "Agar test data mein koi nayi category mile, error mat dena. Usko encoded representation mein ignore/zero-handle kar dena."
encoder = OneHotEncoder(handle_unknown= "ignore")

In [56]:
#  See on which data you're going to do one hot encoding
x_train[categorical_cols]

,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Motivation_Level,Internet_Access,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender
5810,Low,High,Yes,High,Yes,Low,Medium,Public,Negative,No,College,Moderate,Female
1268,High,Medium,Yes,Medium,Yes,Low,High,Public,Neutral,No,High School,Moderate,Female
414,Low,Medium,No,Low,Yes,Low,Medium,Public,Neutral,No,College,Far,Male
4745,High,Medium,Yes,Medium,Yes,Medium,Medium,Public,Neutral,No,High School,Near,Male
654,High,Low,Yes,Medium,Yes,Low,Medium,Private,Positive,No,High School,Near,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3772,Medium,Medium,Yes,Medium,Yes,Low,High,Public,Negative,No,High School,Moderate,Female
5191,Medium,Medium,Yes,High,Yes,Low,Medium,Public,Negative,No,College,Near,Female
5226,High,Low,Yes,Medium,Yes,High,Medium,Public,Positive,No,High School,Moderate,Female
5390,High,High,Yes,Medium,Yes,High,Medium,Public,Positive,No,High School,Near,Male
860,Medium,Low,No,High,Yes,Low,High,Private,Positive,Yes,Postgraduate,Far,Male

In [57]:
# Encoder mein fit kardiya
encoder.fit(x_train[categorical_cols])

OneHotEncoder(handle_unknown='ignore')

In [58]:
# Now transform
x_train_encoded = encoder.transform(x_train[categorical_cols])

In [59]:
x_train_encoded.shape

(5285, 37)

In [60]:
# 13 categorical columns → 37 columns aaye.
# Har categorical column mein alag alag categories hain such as some have 2 some have 3 , as private, international , govt, etc
# sab categories combine hokar 37 encoded columns bane.

In [61]:
x_test_encoded = encoder.transform(x_test[categorical_cols])

In [62]:
x_test_encoded.shape

(1322, 37)

### Ab humein 6 numerical features + 37 encoded categorical features combine karne hain:

In [63]:
numerical_cols = x.select_dtypes('number').columns

In [64]:
numerical_cols

Index(['Hours_Studied', 'Attendance', 'Sleep_Hours', 'Previous_Scores',
       'Tutoring_Sessions', 'Physical_Activity'],
      dtype='object')

#### But one small issue first: X_train_encoded and X_test_encoded are currently sparse matrices, while our numerical data is a Pandas DataFrame.
#### So before combining, we'll convert the encoded matrices into normal NumPy arrays.

In [65]:
x_train_encoded = x_train_encoded.toarray()

In [66]:
x_test_encoded = x_test_encoded.toarray()

In [67]:
X_train_numerical = x_train[numerical_cols].to_numpy()
X_test_numerical = x_test[numerical_cols].to_numpy()

In [68]:
import numpy as np

x_train_final = np.hstack((X_train_numerical, x_train_encoded))
x_test_final = np.hstack((X_test_numerical, x_test_encoded))

In [69]:
x_train_final.shape
x_test_final.shape

(1322, 43)

In [70]:
x_train_final

array([[ 27.,  79.,   8., ...,   0.,   1.,   0.],
       [ 16.,  86.,   7., ...,   0.,   1.,   0.],
       [ 22.,  87.,   8., ...,   0.,   0.,   1.],
       ...,
       [ 17.,  64.,  10., ...,   0.,   1.,   0.],
       [ 16., 100.,   7., ...,   0.,   0.,   1.],
       [ 21.,  62.,   6., ...,   0.,   0.,   1.]], shape=(5285, 43))

###                                                       MODEL TRAINING

In [72]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train_final, y_train)

LinearRegression()

### PREDICTION

In [73]:
y_pred = model.predict(x_test_final)

#### Model kitna accurate hai? Iske liye hum y_pred ko y_test ke saath compare karenge.

### EVALUATION

In [ ]:
# ============================================================  MAE  ============================================================
# MAE ka simple meaning:
# Model ki predicted value actual target value se average mein kitni door hai.

# Formula:
# \[
# MAE = \frac{1}{n}\sum |Actual - Predicted|
# \]

from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, y_pred)
print("MAE", mae)

MAE 0.4499495002270728

In [ ]:
# =====================================================   R^2 (R-squared)  ==============================================================
# R² batata hai ki model target (Exam_Score) ke variation ko kitna explain kar paa raha hai.

from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print("R2 score:", r2)

R2 score: 0.7699282240123634

In [77]:
from sklearn.metrics import root_mean_squared_error
rmse = root_mean_squared_error(y_test, y_pred)
print("RMSE", rmse)

RMSE 1.8033527740267283

### RMSE = root(MSE)

### MAE  = 0.4499
### RMSE = 1.8033
### R²   = 0.7699

In [ ]:
# RMSE = 1.80 ka simple meaning
# RMSE roughly batata hai ki prediction errors ka magnitude ~1.8 marks hai, with larger errors getting more weight.
# kyunki RMSE large errors ko heavily penalize karta hai.

### 👍 Ab Linear Regression ka baseline evaluation complete hai.

### Linear Regression coefficients ko freely choose karta hai.
Kabhi-kabhi features ke coefficients unnecessarily bahut bade ho sakte hain, especially jab features ke beech correlation ho. Isse model overfit kar sakta hai.
Ridge ka idea:
Linear Regression + penalty on large coefficients

Mathematically:
\[
Loss = MSE + \alpha \sum_{j=1}^{n} \beta_j^2
\]
Yahan:
- MSE → prediction error
- β → model coefficients
- α → regularization strength
Simple analogy
Linear Regression bolta hai:
"Mujhe training data fit karna hai."

Ridge bolta hai:
"Fit karo, lekin coefficients ko unnecessarily bada mat banana."

Is technique ko L2 Regularization kehte hain.

## Ridge ( L2 Regularization)

In [78]:
from sklearn.linear_model import Ridge
ridge_model = Ridge(alpha=1.0)

In [79]:
ridge_model.fit(x_train_final, y_train)

Ridge()

In [80]:
ridge_y_pred = ridge_model.predict(x_test_final)

In [ ]:
from sklearn.metrics import mean_absolute_error, r2_score, root_mean_squared_error
ridge_mae = mean_absolute_error(y_test, ridge_y_pred)
ridge_r2 = r2_score(y_test, ridge_y_pred)
ridge_rmse = root_mean_squared_error(y_test, ridge_y_pred)

print("Ridge MAE", ridge_mae)
print("Ridge R2", ridge_r2)
print("Ridge RMSE", ridge_rmse)

Ridge MAE 0.4498838279524776
Ridge R2 0.7699396523190414
Ridge RMSE 1.8033079846900135

In [ ]:
ridge_001 = Ridge(alpha=100)
# I calculated by alpha = 1,10,100 - boht tiny improvements the

ridge_001.fit(x_train_final, y_train)

pred_001 = ridge_001.predict(x_test_final)

Here we did Hyperparameter tuning (Uppar and neeche wale code mein)

In [87]:
mae_001 = mean_absolute_error(y_test, pred_001)
r2_001 = r2_score(y_test, pred_001)
rmse_001 = root_mean_squared_error(y_test, pred_001)

print("Alpha 0.01")
print("MAE:", mae_001)
print("R²:", r2_001)
print("RMSE:", rmse_001)

Alpha 0.01
MAE: 0.45365758521676164
R²: 0.7700835610192134
RMSE: 1.8027438885599707

### Lasso Regression (L1)
Lasso uses L1 regularization, jo kuch coefficients ko exactly zero tak push kar sakti hai.

In [89]:
from sklearn.linear_model import Lasso
lasso_model = Lasso(alpha = 0.01)

In [90]:
lasso_model.fit(x_train_final, y_train)

Lasso(alpha=0.01)

In [91]:
lasso_y_pred = lasso_model.predict(x_test_final)

### Evaluation

In [93]:
lasso_mae = mean_absolute_error(y_test, lasso_y_pred)
lasso_rmse = root_mean_squared_error(y_test, lasso_y_pred)
lasso_r2 = r2_score(y_test, lasso_y_pred)

print("Lasso MAE:", lasso_mae)
print("Lasso R²:", lasso_r2)
print("Lasso RMSE:", lasso_rmse)

Lasso MAE: 0.4566897624858194
Lasso R²: 0.7696465641410912
Lasso RMSE: 1.804456292150929

## Save The Model

In [94]:
import joblib

In [96]:
joblib.dump(encoder, "encoder.pkl")

['encoder.pkl']

In [97]:
joblib.dump(model, "linear_regression_model.pkl")

['linear_regression_model.pkl']

In [98]:
joblib.dump(ridge_model, "ridge_model.pkl")

['ridge_model.pkl']

In [99]:
joblib.dump(lasso_model, "lasso_model.pkl")

['lasso_model.pkl']